// Generated by CoffeeScript 1.6.3
(function() {
  var page, scoreMe, scored;

  scoreMe = function() {
    var $checked, correct, img, key, level, rand;
    correct = 1;
    key = [null, 1, 2, 2, 1, 1, 0, 1, 1, 1, 3, null];
    level = ["ZERO points? Is that even possible?", "One point. You can do better hitting answers at random.", "Two points. Hmm, not very good. Next time don't cheat off your neighbor.", "Three points. Ok, could be better. Call us and catch up soon.", "Four points. Hmm, that's fairly low. Wanna be in our circles on Google+?", "Five points. That's about average, but who wants to be average? Let's be Facebook friends.", "Six points. Well, you've beaten the curve.", "Seven points. That's a pretty good score, and seven <em>is</em> one of our favorite numbers.", "Eight points. That's great. You should be proud.", "Nine points. You know us so well. :-)", "Ten points. Perfect score, that's wonderful!"];
    while (count <= 10) {
      $checked = $("input[name=q" + count + "]:checked");
      if ($checked.index("input[name=q" + count + "]") === key[count]) {
        correct++;
      } else {
        $checked.parent().addClass("wrong");
      }
      $("input[name=q" + count + "]:eq(" + key[count] + ")").parent().addClass("correct");
      count++;
    }
    if (correct === 10) {
      $("#not_perfect").hide();
    }
    img = new Image();
    img.onload = function() {
      return $("#number").css("background-image", "url(" + img.src + ")");
    };
    rand = Math.floor(Math.random() * 4);
    img.src = "images/number-" + correct + "-" + rand + ".png";
    $("#score #answer").html(correct);
    $("#level").html(level[correct]);
    $("input[type=radio]").prop("disabled", "disabled");
    $("li").unbind("click");
    return correct;
  };

  scored = false;

  page = 0;

  $("form").change(function() {
    var count, _results;
    count = 1;
    _results = [];
    while (count <= 10) {
      if ($("input[name=q" + count + "]:checked").size() === 1) {
        $("#q" + count + " button.next").removeProp("disabled");
      }
      _results.push(count++);
    }
    return _results;
  });

  $("button.next").click(function() {
    var nextQuestion;
    if (10 === page) {
      scoreMe();
    }
    if (0 === page) {
      scored = false;
      $("input").removeProp("checked").removeProp("disabled");
      $("li:has('input')").removeClass("correct").removeClass("wrong");
      $("li:has('input[type=radio]')").click(function() {
        $(this).children("input[type=radio]").prop("checked", "checked");
        return $("#q" + page + " button.next").removeProp("disabled");
      });
    }
    if (scored === true) {
      return true;
    }
    if (10 > page) {
      nextQuestion = page + 1;
      if ($("input[name=q" + nextQuestion + "]:checked").size() === 0) {
        $("#q" + nextQuestion + " button.next").prop("disabled", "disabled");
      }
    }
    $("#content .page:eq(" + page + ")").animate({
      opacity: 0.1
    }, 300, function() {
      $("#content .page:eq(" + page + ")").hide();
      page++;
      return $("#content .page:eq(" + page + ")").css("opacity", 0.1).show().animate({
        opacity: 1
      }, 300);
    });
    return false;
  });

  $("button.prev").click(function() {
    $("#content .page:eq(" + page + ")").animate({
      opacity: 0.1
    }, 300, function() {
      $("#content .page:eq(" + page + ")").hide();
      page--;
      return $("#content .page:eq(" + page + ")").css("opacity", 0.1).show().animate({
        opacity: 1
      }, 300);
    });
    return false;
  });

  $("#content .page:eq(0)").show();

  $("#q0 button.next").removeProp("disabled");

}).call(this);
